import type { NormalizedDocument } from '../core/types'
import { parseMarkdown } from './markdown'

/**
 * Pre-processes and normalizes mixed output generated by Large Language Models (LLMs)
 * like GPT-4o, Claude 3.5, Gemini 1.5/2.0, DeepSeek, Llama.
 *
 * LLM responses frequently mix:
 * - Markdown headings and lists
 * - Display and inline LaTeX: \[ ... \], \( ... \), $$ ... $$, $ ... $
 * - Embedded HTML tables, divs, spans, breaks, marks
 * - ASCII / box-drawing tables (+---+---+ or ┌───┬───┐)
 * - Admonitions and callouts: > [!NOTE], > [!TIP], > [!WARNING]
 * - Unclosed code blocks from cutoffs
 */
export function normalizeLlmOutput(rawText: string): string {
  if (!rawText) return ''
  let text = rawText

  // 1. Normalize LaTeX Display Math: \[ ... \] -> $$ ... $$
  text = text.replace(/\\\[([\s\S]*?)\\\]/g, (_match, math) => {
    return `\n\n$$\n${math.trim()}\n$$\n\n`
  })

  // 2. Normalize LaTeX Inline Math: \( ... \) -> $ ... $
  text = text.replace(/\\\(([\s\S]*?)\\\)/g, (_match, math) => {
    return `$${math.trim()}$`
  })

  // 3. Fix unclosed code fences at the end of LLM output
  const codeBlockMatches = text.match(/```/g)
  if (codeBlockMatches && codeBlockMatches.length % 2 !== 0) {
    text += '\n```\n'
  }

  // 4. Convert ASCII box tables (+---+---+ style) into standard GFM pipe tables
  text = text.replace(/(?:^[+|].*$\n?){3,}/gm, (tableBlock) => {
    const lines = tableBlock.trim().split('\n')
    const contentLines: string[] = []

    for (const line of lines) {
      // If it's a divider line like +---+---+ or +===+===+
      if (/^\s*\+[=+-]+\+\s*$/.test(line)) {
        if (contentLines.length === 1) {
          // Make it a GFM header separator
          const cols = line.split('+').filter((c) => c.trim().length > 0)
          const gfmDivider = '| ' + cols.map(() => '---').join(' | ') + ' |'
          contentLines.push(gfmDivider)
        }
        continue
      }
      // If it's a data line with pipes | A | B |
      if (line.includes('|')) {
        contentLines.push(line.trim())
      }
    }

    if (contentLines.length >= 2) {
      return '\n' + contentLines.join('\n') + '\n'
    }
    return tableBlock
  })

  // 5. Convert HTML tables to Markdown tables if present in LLM response
  text = text.replace(/<table[\s\S]*?<\/table>/gi, (htmlTable) => {
    try {
      const rows: string[][] = []
      const rowMatches = htmlTable.match(/<tr[\s\S]*?<\/tr>/gi) || []

      for (const rowHtml of rowMatches) {
        const cells: string[] = []
        const cellMatches = rowHtml.match(/<(th|td)[\s\S]*?<\/\1>/gi) || []
        for (const cellHtml of cellMatches) {
          const cleanText = cellHtml
            .replace(/<(th|td)[^>]*>/gi, '')
            .replace(/<\/(th|td)>/gi, '')
            .replace(/<[^>]+>/g, '')
            .trim()
          cells.push(cleanText)
        }
        if (cells.length > 0) rows.push(cells)
      }

      if (rows.length > 0) {
        const header = '| ' + rows[0].join(' | ') + ' |'
        const divider = '| ' + rows[0].map(() => '---').join(' | ') + ' |'
        const bodyRows = rows.slice(1).map((r) => '| ' + r.join(' | ') + ' |')
        return '\n\n' + [header, divider, ...bodyRows].join('\n') + '\n\n'
      }
    } catch {
      // fallback to original if parsing fails
    }
    return htmlTable
  })

  // 6. Convert inline HTML formatting to Markdown where helpful
  text = text
    .replace(/<b\b[^>]*>([\s\S]*?)<\/b>/gi, '**$1**')
    .replace(/<strong\b[^>]*>([\s\S]*?)<\/strong>/gi, '**$1**')
    .replace(/<i\b[^>]*>([\s\S]*?)<\/i>/gi, '*$1*')
    .replace(/<em\b[^>]*>([\s\S]*?)<\/em>/gi, '*$1*')
    .replace(/<code\b[^>]*>([\s\S]*?)<\/code>/gi, '`$1`')
    .replace(/<mark\b[^>]*>([\s\S]*?)<\/mark>/gi, '==$1==')
    .replace(/<br\s*\/?>/gi, '\n')

  return text
}

/**
 * Parses mixed LLM output into the unified NormalizedDocument AST
 */
export function parseLlmMixed(rawText: string): NormalizedDocument {
  const normalized = normalizeLlmOutput(rawText)
  const doc = parseMarkdown(normalized)
  doc.metadata.sourceFormat = 'llm-mixed'
  return doc
}
